Upgrade to yeoman-generator 2.0.5
iamstarkov/generator-git-init pull request #9
Opened 2018-05-21 18:55 UTC by bn3t

This is to avoid security vulnerabilities in older yeoman generator.

2018-05-21 19:53 UTC, bn3t commented
I had to remove the ability to use commit: true and not specifying a commit message. This was not working, at least as of Yeoman v2. The value received by the method is coerced to a String. Because of this, the commit message was "true" and not "init" like expected.

2018-10-17 09:28 UTC, Razzeee commented
So what's the plan here, will you create a new npm package with this?

2018-10-17 12:44 UTC, iamstarkov commented on generators/app/index.js
>      this.option('commit', { type: String, required: false, alias: 'c',
should be required then
```suggestion
    this.option('commit', { type: String, required: true, alias: 'c',
```

2018-10-17 12:45 UTC, iamstarkov commented
I can give read-write permissions to the GitHub repo and nom package if anyone wants to steer the development

2018-10-17 12:47 UTC, iamstarkov requested changes
PR needs more changes to reflect the intention

2018-10-17 20:55 UTC, Razzeee commented
Whatever it takes to fix the security problem, even if it's unlikely that it's really an attack vector on a yeoman config.

2025-02-16 15:59 UTC, closed without merging